# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jessica Strein
email: jessica.strein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Jessica Strein and I love programming and biology. I create workflows for data analysis
  using multiple computer languages, and I have developed web applications using R Shiny.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jess28.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jess28
include: ['projects']

# Build settings
markdown: kramdown
